name: Spark Connector Integration Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: IT
    runs-on: ubuntu-latest
    strategy:
     matrix:
       scala_version: [ '2.12.11' ]
       spark_version: [ '3.0.0' ]
       use_copy_unload: [ 'true', 'false' ]
       # The test on gcp hangs because of the timeout when downloading data
       # chunks from GCP. It is not a Spark Connector issue because the test
       # runs well on Travis and local. SNOW-177689 is filed to investigate it
       # Before that, the test on GCP is disabled to avoid blocking others.
       # cloud_provider: [ 'aws', 'azure', 'gcp' ]
       cloud_provider: [ 'aws', 'azure' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Decrypt snowflake.json for testing
      run: ./.github/scripts/decrypt_secret.sh snowflake.travis.json snowflake.travis.json.gpg
      env:
        SNOWFLAKE_TEST_CONFIG_SECRET: ${{ secrets.SNOWFLAKE_TEST_CONFIG_SECRET }}

    - name: Run tests
      run: ./.github/scripts/run-tests-github.sh
      env:
        INTEGRATION_TESTS: true
        SPARK_SCALA_VERSION: ${{ matrix.scala_version }}
        SPARK_VERSION: ${{ matrix.spark_version }}
        SNOWFLAKE_TEST_ACCOUNT: ${{ matrix.cloud_provider }}
        SPARK_CONN_ENV_USE_COPY_UNLOAD: ${{ matrix.use_copy_unload }}

    - name: Update test coverage report
      run: bash <(curl -s https://codecov.io/bash)
